AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AppName:
    Type: String
  VPCID:
    Type: String
  PublicSubnet:
    Type: String
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
  MyIpAddress:
    Type: String
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${AppName}-test-ec2
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIpAddress
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-northeast-1a
      ImageId: ami-052652af12b58691f # amazon linux 2
      InstanceType: t3.micro
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref SecurityGroup
      SubnetId: !Ref PublicSubnet
      Tenancy: default